// Code generated by xgen. DO NOT EDIT.

package main

// EinheitStromSpeicher ...
type EinheitStromSpeicher struct {
	EinheitMastrNummer                           string  `xml:"EinheitMastrNummer"                      gorm:"primaryKey"`
	DatumLetzteAktualisierung                    string  `xml:"DatumLetzteAktualisierung"`
	LokationMaStRNummer                          string  `xml:"LokationMaStRNummer"`
	NetzbetreiberpruefungStatus                  int16   `xml:"NetzbetreiberpruefungStatus"`
	NetzbetreiberpruefungDatum                   string  `xml:"NetzbetreiberpruefungDatum"`
	AnlagenbetreiberMastrNummer                  string  `xml:"AnlagenbetreiberMastrNummer"`
	Land                                         int16   `xml:"Land"`
	Bundesland                                   int16   `xml:"Bundesland"`
	Landkreis                                    string  `xml:"Landkreis"`
	Gemeinde                                     string  `xml:"Gemeinde"`
	Gemeindeschluessel                           string  `xml:"Gemeindeschluessel"`
	Postleitzahl                                 string  `xml:"Postleitzahl"`
	Gemarkung                                    string  `xml:"Gemarkung"`
	FlurFlurstuecknummern                        string  `xml:"FlurFlurstuecknummern"`
	Strasse                                      string  `xml:"Strasse"`
	StrasseNichtGefunden                         int8    `xml:"StrasseNichtGefunden"                    gorm:"-"`
	Hausnummer                                   string  `xml:"Hausnummer"`
	Hausnummernv                                 int8    `xml:"Hausnummer_nv"                           gorm:"-"` 
	HausnummerNichtGefunden                      int8    `xml:"HausnummerNichtGefunden"                 gorm:"-"`
	Adresszusatz                                 string  `xml:"Adresszusatz"`
	Ort                                          string  `xml:"Ort"`
	Laengengrad                                  float32 `xml:"Laengengrad"`
	Breitengrad                                  float32 `xml:"Breitengrad"`
	Registrierungsdatum                          string  `xml:"Registrierungsdatum"`
	Inbetriebnahmedatum                          string  `xml:"Inbetriebnahmedatum"`
	GeplantesInbetriebnahmedatum                 string  `xml:"GeplantesInbetriebnahmedatum"`
	DatumEndgueltigeStilllegung                  string  `xml:"DatumEndgueltigeStilllegung"`
	DatumBeginnVoruebergehendeStilllegung        string  `xml:"DatumBeginnVoruebergehendeStilllegung"`
	DatumWiederaufnahmeBetrieb                   string  `xml:"DatumWiederaufnahmeBetrieb"`
	EinheitSystemstatus                          int16   `xml:"EinheitSystemstatus"`
	EinheitBetriebsstatus                        int8    `xml:"EinheitBetriebsstatus"`
	BestandsanlageMastrNummer                    string  `xml:"BestandsanlageMastrNummer"`
	NichtVorhandenInMigriertenEinheiten          int8    `xml:"NichtVorhandenInMigriertenEinheiten"      gorm:"-"`
	AltAnlagenbetreiberMastrNummer               string  `xml:"AltAnlagenbetreiberMastrNummer"`
	DatumDesBetreiberwechsels                    string  `xml:"DatumDesBetreiberwechsels"`
	DatumRegistrierungDesBetreiberwechsels       string  `xml:"DatumRegistrierungDesBetreiberwechsels"`
	NameStromerzeugungseinheit                   string  `xml:"NameStromerzeugungseinheit"`
	Weic                                         string  `xml:"Weic"`
	Weicnv                                       int8    `xml:"Weic_nv"`
	WeicDisplayName                              string  `xml:"WeicDisplayName"`
	Kraftwerksnummer                             string  `xml:"Kraftwerksnummer"`
	Kraftwerksnummernv                           int8    `xml:"Kraftwerksnummer_nv"`
	Energietraeger                               int16   `xml:"Energietraeger"`
	Bruttoleistung                               float32 `xml:"Bruttoleistung"`
	Nettonennleistung                            float32 `xml:"Nettonennleistung"`
	AnschlussAnHoechstOderHochSpannung           int8    `xml:"AnschlussAnHoechstOderHochSpannung"`
	Einsatzverantwortlicher                      string  `xml:"Einsatzverantwortlicher"`
	FernsteuerbarkeitNb                          int8    `xml:"FernsteuerbarkeitNb"`
	FernsteuerbarkeitDv                          int8    `xml:"FernsteuerbarkeitDv"`
	Einspeisungsart                              int16   `xml:"Einspeisungsart"`
	Einsatzort                                   int16   `xml:"Einsatzort"`
	GenMastrNummer                               string  `xml:"GenMastrNummer"`
	ReserveartNachDemEnWG                        int16   `xml:"ReserveartNachDemEnWG"`
	DatumUeberfuehrungInReserve                  string  `xml:"DatumUeberfuehrungInReserve"`
	AcDcKoppelung                                int16   `xml:"AcDcKoppelung"`
	Batterietechnologie                          int16   `xml:"Batterietechnologie"`
	Notstromaggregat                             int8    `xml:"Notstromaggregat"`
	PumpbetriebLeistungsaufnahme                 float32 `xml:"PumpbetriebLeistungsaufnahme"`
	PumpbetriebKontinuierlichRegelbar            int8    `xml:"PumpbetriebKontinuierlichRegelbar"`
	Pumpspeichertechnologie                      int16   `xml:"Pumpspeichertechnologie"`
	BestandteilGrenzkraftwerk                    int8    `xml:"BestandteilGrenzkraftwerk"`
	NettonennleistungDeutschland                 float32 `xml:"NettonennleistungDeutschland"`
	ZugeordnenteWirkleistungWechselrichter       float32 `xml:"ZugeordnenteWirkleistungWechselrichter"`
	SpeMastrNummer                               string  `xml:"SpeMastrNummer"`
	EegMaStRNummer                               string  `xml:"EegMaStRNummer"`
	EegAnlagentyp                                int16   `xml:"EegAnlagentyp"`
	Technologie                                  int16   `xml:"Technologie"`
	GemeinsamRegistrierteSolareinheitMastrNummer string  `xml:"GemeinsamRegistrierteSolareinheitMastrNummer"`
}

// EinheitenStromSpeicher ...
type EinheitenStromSpeicher struct {
	EinheitStromSpeicher []*EinheitStromSpeicher `xml:"EinheitStromSpeicher"`
}

// Technologie ...
type Technologie int16
