// Code generated by xgen. DO NOT EDIT.

package main

// EinheitSolar ...
type EinheitSolar struct {
	EinheitMastrNummer                       string  `xml:"EinheitMastrNummer"                      gorm:"primaryKey"`
	DatumLetzteAktualisierung                string  `xml:"DatumLetzteAktualisierung"`
	LokationMastrNummer                      string  `xml:"LokationMaStRNummer"`
	NetzbetreiberpruefungStatus              int16   `xml:"NetzbetreiberpruefungStatus"`
	NetzbetreiberpruefungDatum               string  `xml:"NetzbetreiberpruefungDatum"`
	AnlagenbetreiberMastrNummer              string  `xml:"AnlagenbetreiberMastrNummer"`
	Land                                     int16   `xml:"Land"`
	Bundesland                               int16   `xml:"Bundesland"`
	Landkreis                                string  `xml:"Landkreis"`
	Gemeinde                                 string  `xml:"Gemeinde"`
	Gemeindeschluessel                       string  `xml:"Gemeindeschluessel"`
	Postleitzahl                             string  `xml:"Postleitzahl"`
	Strasse                                  string  `xml:"Strasse"`
	Gemarkung                                string  `xml:"Gemarkung"`
	FlurFlurstuecknummern                    string  `xml:"FlurFlurstuecknummern"`
	StrasseNichtGefunden                     int8    `xml:"StrasseNichtGefunden"                    gorm:"-"`
	Hausnummer                               string  `xml:"Hausnummer"`
	Hausnummernv                             int8    `xml:"Hausnummer_nv"                           gorm:"-"`
	HausnummerNichtGefunden                  int8    `xml:"HausnummerNichtGefunden"                 gorm:"-"`
	Adresszusatz                             string  `xml:"Adresszusatz"`
	Ort                                      string  `xml:"Ort"`
	Laengengrad                              float32 `xml:"Laengengrad"`
	Breitengrad                              float32 `xml:"Breitengrad"`
	Registrierungsdatum                      string  `xml:"Registrierungsdatum"`
	Inbetriebnahmedatum                      string  `xml:"Inbetriebnahmedatum"`
	DatumEndgueltigeStilllegung              string  `xml:"DatumEndgueltigeStilllegung"`
	DatumBeginnVoruebergehendeStilllegung    string  `xml:"DatumBeginnVoruebergehendeStilllegung"`
	DatumWiederaufnahmeBetrieb               string  `xml:"DatumWiederaufnahmeBetrieb"`
	GeplantesInbetriebnahmedatum             string  `xml:"GeplantesInbetriebnahmedatum"`
	EinheitSystemstatus                      int16   `xml:"EinheitSystemstatus"`
	EinheitBetriebsstatus                    int8    `xml:"EinheitBetriebsstatus"`
	BestandsanlageMastrNummer                string  `xml:"BestandsanlageMastrNummer"`
	NichtVorhandenInMigriertenEinheiten      int8    `xml:"NichtVorhandenInMigriertenEinheiten"     gorm:"-"`
	AltAnlagenbetreiberMastrNummer           string  `xml:"AltAnlagenbetreiberMastrNummer"`
	DatumDesBetreiberwechsels                string  `xml:"DatumDesBetreiberwechsels"`
	DatumRegistrierungDesBetreiberwechsels   string  `xml:"DatumRegistrierungDesBetreiberwechsels"`
	NameStromerzeugungseinheit               string  `xml:"NameStromerzeugungseinheit"`
	Weic                                     string  `xml:"Weic"`
	Weicnv                                   int8    `xml:"Weic_nv"`
	WeicDisplayName                          string  `xml:"WeicDisplayName"`
	Kraftwerksnummer                         string  `xml:"Kraftwerksnummer"`
	Kraftwerksnummernv                       int8    `xml:"Kraftwerksnummer_nv"`
	Energietraeger                           int16   `xml:"Energietraeger"`
	Bruttoleistung                           float32 `xml:"Bruttoleistung"`
	Nettonennleistung                        float32 `xml:"Nettonennleistung"`
	AnschlussAnHoechstOderHochSpannung       int8    `xml:"AnschlussAnHoechstOderHochSpannung"`
	FernsteuerbarkeitNb                      int8    `xml:"FernsteuerbarkeitNb"`
	FernsteuerbarkeitDv                      int8    `xml:"FernsteuerbarkeitDv"`
	Einspeisungsart                          int16   `xml:"Einspeisungsart"`
	ZugeordneteWirkleistungWechselrichter    float32 `xml:"ZugeordneteWirkleistungWechselrichter"`
	AnzahlModule                             int     `xml:"AnzahlModule"`
	Lage                                     int16   `xml:"Lage"`
	Leistungsbegrenzung                      int16   `xml:"Leistungsbegrenzung"`
	EinheitlicheAusrichtungUndNeigungswinkel int8    `xml:"EinheitlicheAusrichtungUndNeigungswinkel"`
	Hauptausrichtung                         int16   `xml:"Hauptausrichtung"`
	HauptausrichtungNeigungswinkel           int16   `xml:"HauptausrichtungNeigungswinkel"`
	Nebenausrichtung                         int16   `xml:"Nebenausrichtung"`
	NebenausrichtungNeigungswinkel           int16   `xml:"NebenausrichtungNeigungswinkel"`
	Nutzungsbereich                          int16   `xml:"Nutzungsbereich"`
	Buergerenergie                           int8    `xml:"Buergerenergie"`
	EegMastrNummer                           string  `xml:"EegMaStRNummer"`
	InAnspruchGenommeneFlaeche               float32 `xml:"InAnspruchGenommeneFlaeche"`
	ArtDerFlaecheIds                         string  `xml:"ArtDerFlaecheIds"`
	InAnspruchGenommeneAckerflaeche          float32 `xml:"InAnspruchGenommeneAckerflaeche"`
	Einsatzverantwortlicher                  string  `xml:"Einsatzverantwortlicher"`
	GenMastrNummer                           string  `xml:"GenMastrNummer"`
}

// EinheitenSolar ...
type EinheitenSolar struct {
	EinheitSolar []*EinheitSolar `xml:"EinheitSolar"`
}

// Buergerenergie ...
type Buergerenergie []int8
